# Generated by Django 5.1.1 on 2024-09-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("number", models.PositiveIntegerField(unique=True)),
                ("is_occupied", models.BooleanField(default=False)),
                ("occupation_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
