# Generated by Django 5.1.1 on 2024-09-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="court",
            name="location",
        ),
        migrations.AddField(
            model_name="court",
            name="is_occupied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="court",
            name="number",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="court",
            name="occupation_time",
            field=models.DateTimeField(null=True),
        ),
    ]
