# Generated by Django 5.1.1 on 2024-09-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0002_remove_court_location_court_is_occupied_court_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="occupation_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
