# Generated by Django 5.1.1 on 2024-09-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_court_occupation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='occupation_time',
            field=models.DateTimeField(null=True),
        ),
    ]
