# Generated by Django 5.1.1 on 2024-09-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_alter_court_occupation_time"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Court",
        ),
    ]
