# Generated by Django 5.1.1 on 2024-09-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_delete_court"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="trainer",
        ),
        migrations.DeleteModel(
            name="Trainer",
        ),
    ]
