# Generated by Django 5.1.1 on 2024-09-16 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        ('members', '0008_member_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='courts.court'),
        ),
    ]
