# Generated by Django 5.1.1 on 2024-09-17 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_alter_member_court"),
        ("trainers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="trainer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trainees",
                to="trainers.trainer",
            ),
        ),
    ]
