# Generated by Django 5.1.1 on 2024-09-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='trainer',
        ),
    ]
